
version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: fyyur
      POSTGRES_USER: fyyur_user
      POSTGRES_PASSWORD: fyyur_password

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fyyur_user -d fyyur"]
      interval: 5s
      timeout: 5s
      retries: 5
